# Array creation:Conversion from other python structure

In [2]:
import numpy as np

In [3]:
listarray=np.array([[1,5,3],[8,4,3],[0,3,2]])

In [4]:
listarray

array([[1, 5, 3],
       [8, 4, 3],
       [0, 3, 2]])

In [5]:
listarray.dtype

dtype('int64')

In [6]:
listarray.shape

(3, 3)

In [7]:
listarray.size

9

In [8]:
np.array({34,45,21})

array({34, 45, 21}, dtype=object)

In [9]:
zeros=np.zeros((2,5))

In [10]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
rng=np.arange(15)

In [13]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
lspace=np.linspace(1,5,12)

In [15]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [16]:
emp=np.empty((4,6))

In [17]:
emp

array([[1.35153219e-316, 0.00000000e+000, 6.90286899e-310,
        6.90287399e-310, 6.90286899e-310, 6.90287399e-310],
       [6.90286899e-310, 6.90287399e-310, 6.90286899e-310,
        6.90287399e-310, 6.90286899e-310, 6.90287399e-310],
       [6.90287399e-310, 6.90287399e-310, 6.90287399e-310,
        6.90287399e-310, 6.90287399e-310, 6.90287399e-310],
       [6.90286898e-310, 6.90286898e-310, 6.90286898e-310,
        6.90287399e-310, 6.90286898e-310, 1.92751293e-316]])

In [18]:
emp_like=np.empty_like(lspace)

In [19]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [20]:
ide=np.identity(45)

In [21]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [22]:
ide.shape

(45, 45)

In [23]:
arr=np.arange(99)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [26]:
arr=arr.reshape(3,33)

In [27]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [29]:
arr=arr.ravel()

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [31]:
arr.shape

(99,)