In [1]:
import numpy as np

In [2]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [3]:
ar=np.array(x)

In [4]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [5]:
ar.sum(axis=0)

array([12,  8,  9])

In [6]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [7]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [8]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [9]:
ar.flat

In [10]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [11]:
ar.ndim

2

In [12]:
ar.size

9

In [13]:
ar.nbytes

72

In [14]:
one=np.array([1,2,3,4,78,2])

In [15]:
one.argmax()

4

In [16]:
one.armin()

AttributeError: 'numpy.ndarray' object has no attribute 'armin'

In [17]:
one.argmin()

0

In [18]:
one.argsort()

array([0, 1, 5, 2, 3, 4])

In [19]:
ar.argmin()

8

In [20]:
ar.argmax()

6

In [21]:
ar.argmax(axis=0)

array([2, 1, 1])

In [22]:
ar.argmax(axis=1)

array([2, 2, 0])

In [23]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [24]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [25]:
one.argsort()

array([0, 1, 5, 2, 3, 4])

In [26]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [27]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [28]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [29]:
ar2=np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [30]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [31]:
[34,6]+[58,87]

[34, 6, 58, 87]

In [32]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [33]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [34]:
ar.sum()

29

In [35]:
ar.max()

7

In [36]:
ar.min()

0

In [37]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [38]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [39]:
np.count_nonzero(ar)

8

In [40]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [41]:
ar[1,2]=0

In [42]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 0, 1]))

In [43]:
import sys

In [44]:
py_ar=[0,4,55,2]

In [45]:
np_ar=np.array(py_ar)

In [46]:
sys.getsizeof(1)*len(py_ar)

112

In [47]:
np_ar.itemsize*np_ar.size

32

In [48]:
np_ar.tolist()

[0, 4, 55, 2]